import { Component, input, ChangeDetectionStrategy } from '@angular/core';
import {
  LucideDynamicIcon,
  LucideActivity,
  LucideLayoutDashboard,
  LucidePackage,
  LucideScanBarcode,
  LucideFileScan,
  LucideShieldCheck,
  LucideChevronLeft,
  LucideChevronRight,
  LucideMenu,
  LucideLogOut,
  LucidePlus,
  LucideSearch,
  LucideX,
  LucideCheck,
  LucideTriangleAlert,
  LucideArrowRight,
  LucideArrowLeft,
  LucideTrash2,
  LucideBarcode,
  LucideFingerprint,
  LucideWarehouse,
  LucideUpload,
  LucideDownload,
  LucideEye,
  LucideEyeOff,
  LucideMail,
  LucideLockKeyhole,
  LucideInbox,
  LucideListChecks,
  LucideCircleCheck,
  LucideCircleX,
  LucideTruck,
  LucideCpu,
  LucideArrowUpRight,
  LucideVolume2,
  LucideMapPin,
  LucideHistory,
  LucideArrowLeftRight,
  LucideShoppingCart,
  LucideArrowDownToLine,
  LucideArrowUpFromLine,
  LucideSlidersHorizontal,
  LucidePlug,
  LucideRefreshCw,
} from '@lucide/angular';
const icons: Record<string, any> = {
  activity: LucideActivity,
  dashboard: LucideLayoutDashboard,
  package: LucidePackage,
  scan: LucideScanBarcode,
  file: LucideFileScan,
  shield: LucideShieldCheck,
  left: LucideChevronLeft,
  right: LucideChevronRight,
  menu: LucideMenu,
  logout: LucideLogOut,
  plus: LucidePlus,
  search: LucideSearch,
  x: LucideX,
  check: LucideCheck,
  alert: LucideTriangleAlert,
  arrow: LucideArrowRight,
  back: LucideArrowLeft,
  trash: LucideTrash2,
  barcode: LucideBarcode,
  serial: LucideFingerprint,
  warehouse: LucideWarehouse,
  upload: LucideUpload,
  download: LucideDownload,
  eye: LucideEye,
  hidden: LucideEyeOff,
  mail: LucideMail,
  lock: LucideLockKeyhole,
  inbox: LucideInbox,
  list: LucideListChecks,
  ok: LucideCircleCheck,
  error: LucideCircleX,
  truck: LucideTruck,
  cpu: LucideCpu,
  trend: LucideArrowUpRight,
  sound: LucideVolume2,
  pin: LucideMapPin,
  history: LucideHistory,
  swap: LucideArrowLeftRight,
  sale: LucideShoppingCart,
  in: LucideArrowDownToLine,
  out: LucideArrowUpFromLine,
  adjust: LucideSlidersHorizontal,
  plug: LucidePlug,
  refresh: LucideRefreshCw,
};
@Component({
  selector: 'gx-icon',
  standalone: true,
  imports: [LucideDynamicIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template:
    '<svg [lucideIcon]="icons[name()] || icons[\'package\']" [size]="size()" [strokeWidth]="1.6"></svg>',
  host: { 'aria-hidden': 'true', class: 'gx-icon' },
})
export class Icon {
  name = input('package');
  size = input(18);
  icons = icons;
}
